spdx/spdx-java-tagvalue-store

- src/main/java/org/spdx/tag/BuildDocument.java
> Fix missing line number for file error reporting

- src/main/java/org/spdx/tag/BuildDocument.java
- src/test/java/org/spdx/tag/TestBuildDocument.java
> Resolve issue #11 - allow no spaces in exteral doc ref

- pom.xml
- src/main/java/org/spdx/tag/BuildDocument.java
Resolves issue #16   Also updates to the latest SPDX java library (unrelated to issue 16).
> Handle consecutive snippet definitions

- pom.xml
- src/main/java/org/spdx/tag/BuildDocument.java
Necessary fix for https://github.com/spdx/Spdx-Java-Library/issues/69
> Check for duplicate relationships when adding relationships

- src/main/java/org/spdx/tag/CommonCode.java
- src/test/java/org/spdx/tagvaluestore/TagValueStoreTest.java
- testResources/SPDXTagExample-v2.3.spdx
> Fix NOASSERTION for File and Snippet copyright

- pom.xml
> Update SPDX Java Library version

- src/main/java/org/spdx/tag/BuildDocument.java
- src/test/java/org/spdx/tagvaluestore/TagValueStoreTest.java
- testResources/artifactof.spdx
> Fix relationship for artifactOf

- pom.xml
> Update SPDX Java library to version 1.1.2

- pom.xml
> Update SPDX Java Library and add dependency-check

- src/main/java/org/spdx/tag/BuildDocument.java
- src/test/java/org/spdx/tag/TestBuildDocument.java
> Remove dummy extracted license text

- src/main/java/org/spdx/tag/BuildDocument.java
> Check for proper extracted license info ID's

- src/main/java/org/spdx/tag/CommonCode.java
> Change sort order for files and packages

- pom.xml
> Update SPDX Java library to version 1.1.4

- src/main/java/org/spdx/tag/BuildDocument.java
> Issue a warning when more than one extracted license uses the same ID

- src/main/java/org/spdx/tag/CommonCode.java
> Add relationship comment to output

- src/main/java/org/spdx/tag/BuildDocument.java
- src/test/java/org/spdx/tag/TestBuildDocument.java
Fixes unit test failures exposed by
https://github.com/spdx/Spdx-Java-Library/pull/159
> Verify relationships after all relationships added

- RELEASE-CHECKLIST.md
- pom.xml
- src/test/java/org/spdx/tagvaluestore/TagValueStoreTest.java
> Update POM to use the release plugin

- pom.xml
- src/main/java/org/spdx/tag/BuildDocument.java
- src/main/java/org/spdx/tag/CommonCode.java
- src/main/java/org/spdx/tag/InvalidFileFormatException.java
- src/main/java/org/spdx/tag/InvalidSpdxTagFileException.java
- src/main/java/org/spdx/tag/RecognitionException.java
- src/main/java/org/spdx/tagvaluestore/TagValueStore.java
- src/test/java/org/spdx/tag/TestBuildDocument.java
- src/test/java/org/spdx/tagvaluestore/TagValueStoreTest.java
NOTE: There are several breaking changes - supports the new store interface for SPDX Java Library version 2+
> Updates to support SPDX Spec version 3

- src/main/java/org/spdx/tag/CommonCode.java
> Add attributionText to snippets

- src/main/java/org/spdx/tag/CommonCode.java
> Output files analyzed tag after relationships

- src/main/java/org/spdx/tag/BuildDocument.java
- src/test/java/org/spdx/tagvaluestore/TagValueStoreTest.java
- testResources/dashes.spdx
> Allow for dashes in primary purpose
